---
title: "Ewolucja o co z nią chodzi? Mała powtóreczka z psych ewolucyjnej, zanim się w to wgłębie"
author: "Agata Zywert"
date: "26 kwietnia 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

`muszę to zapisać, bo inaczej nigdy tego nie zapamiętam`
### "Jakie laski wolą faceci, podejście oczywiste"

* Przede wszystkim chodzi o to, że faceci muszą się łączyć z takimi laskami, dzięki którym mogą mieć sukces reprodukcyjny.
Co za tym idzie muszą to być typiary, które dadzą im potomstwo, ale najlepiej żeby było ich więcej, bo im więcej kobiet do rodzenia, tym więcej potomstwa.
* Ogólnie stąd też jest to (podobno) dlaczego chłopcy wolą młodsze laski (jak sami są starsi), bo młodsza = większe prawdopodobieństwo sukcesu reprodukcyjnego
* Stosunek talii do bioder XD

`To wszystko jest obvious as fuck`
### Co więcej na ten temat mów David Buss w Psych Ewolucyjnej??


#### "Męskie strategie doboru **STAŁEJ** partnerki"

* Ten Pan pisze, że faceci są zainteresowani stałym związkiem, bo inaczej nie zaliczą XD W sensie, że bez oznak zaangażowania ze strony mężczyzn, kobiety się z nim nie prześpią i jak nie będzie zainteresowany stałym związkiem to może być odrzucony przez wszystkie kobiety.
* Do tego - "inną korzyścią czerpaną przez mężczyzn z małżeńswtwa jest możliwość zdobycia lepszej partnerki" `o jak kisne XD`, zajęci faceci (czyli ze potrafią chronić rodzinę) przyciagają atrakcyjne kobiety `z tego kisne jeszcze bardziej`
* 3 korzyścią jest to, że jest większa pewność, że jest się ojcem swojego dziecka
        
        tak naprawdę mi to zwisa, bo w tym badaniu nie chodzi o stały związek ale co ja tam wiem

* Potem pisze to samo co napisałam u góry, młode, ładne, krągłe
* No i następuję coś ciekawszego -> Wpływ kontekstu na wybór partnerki przez mężczyzne - czyli, że jedni mają wybór a drudzy nie, no i Ci bez pozycji i zasobów (_można np. sb zawnioskować, że mają niższą samoocenę i np. ktos to udowodnil_) - częściej godzą się na partnerkę "mniej idealną"
* "Osoby podkreślające swą atrakcyjność fizyczną dostawały więcej odpowiedzi niezależnie od płci, to jednak znacznie więcej takich odpowiedzi otrzymywały kobiety. Co interesujące, kobiety wspominające w ogłoszeniach o swej atrakcyjności seksualnej otrzymywały _znacznie_ więcej listów niż te, które pomijały ten aspekt. W wypadku mężczyzn było odwrotnie(...) kobiety odbierały reklamowanie przez mężczyzn własnej seksualności jako sygnał, że zależy im na przelotnych znajomościach, nie na stałym związku"

#### PRZELOTNE KONTAKTY SEKSUALNE

##### **Męskie korzyści adaptacyjne z kontaktów przelotnych**

* u mężczyzn w drodze ewolucji ukształtowało się silniejsze pragnienie takich kontaktów, bo laski są obciążone tym, że będą musiały 9 miechów tachać dziecię a potem jeszcze je mieć, a faceci nie mają żadnego obciążenia
* Mężczyzna odnosi z seksu przelotnego bezpośrednie korzyści reprodukcyjne: zwiększał liczbę spłodzonego potomwstwa
* W przeszłości sukces reprodukcyjny faceta rósł wraz z ilością partnerek a nie ilością dzieci z jedną i tą samą (Betzig i Dawkins 1986)

##### **Problemy adaptacyjne  mężczyzn nawiązujących  kontakty  przelotne**
* Pożądanie coś tam
* To co będzie niżej, że obniżenie wymagań
* _**Chodzi  o  to,  aby  zabiegi mające na celu uzyskanie dostępu seksualnego do kobiety,  nie trwały zbyt długo.  Im mniej czasu  zajmują, z tym większą liczbą kobiet  dany  mężczyzna  może  kopulować. Długotrwale zabiegi, podobnie jak wysokie wymagania, przeszkadzają funkcjonowaniu  mechanizmu  adaptacyjnego  nastawianego  na  maksymalizowanie  liczby  partnerek.**_

#### TO JEST WAŻNE AS FUCK DLA MNIE - JAK LASKA JEST "ŁATWIEJSZA" TO KRÓCEJ TRZEBA JĄ ZDOBYWAĆ WIĘC JĄ WOLĄ!!!! TO NIŻEJ TEŻ TO MÓWI: 

* **Mężczyźni,  jako  pleć  mniej  inwestująca,  powinni być mniej wybredni w doborze przelotnych  partnerek.  Największe  korzyści reprodukcyjne  osiągają  ci,  którzy  kierująswoje  zabiegi  ku  kobietom  dostępnym seksualnie.  Angażowanie  czasu  i  energii w  staranie  się  o  względy  kobiety,  która prawdopodobnie  nie  zgodzi  się  na  seks, stoi w sprzeczności ze strategią kontaktów przelotnych**


Ma jeszcze książkę "Ewolucja pożądania i są w niej rzeczki takie o:

* _"(...) mechanizmem psychologicznym umożliwiającym mężczyznom liczne kontakty przelotne, jest obniżenie wymagań w stosunku do partnerki_ `czy za tym idzie że te słabe tak naprawdę oceniają na spoko jesli są latwiejsze?`
* Było badanie i trzeba było określić przedział wieku dla związku stałego i dla ONS i ONS ten przedział by o wiele wiekszy
* Generalnie nieważne co to są za cechy (morda, życzliwość, sylwetka, odpowiedzialność, spontaniczność etc etc) zawsze są obniżone jeśli chodzi o ONS a nie o trwały związek
* ten syndrom, że zamknięcie baru i _"(...) Badania  psychologiczne  wskazują jednak,że  przyczyną „wzrostu”  są raczej  malejące  szanse  znalezienia  sobie  kogoś na  daną noc.   „Wzrost”   atrakcyjności   znajdujących   się w   pobliżu   kobiet   jest   psychologicznym mechanizmem ułatwiającym przelotny kontakt seksualny."
* "Kobiecą korzyścią z  przelotnego  seksu  było  natomiast  powiększenie  dostępu  do niezbędnych   do   przeżycia   zasobów. " `no nie mogę xDDDDDDDD`
* **ZŁOTA MYŚL:** Żadne związki społeczne nie są wolne od wszechobecnego wpływu doboru seksualnego.

`powinnam zostać wykładowcą`
`byłabym zajebista w mówieniu o tym wszystkim`

##### **Coś kolejnego oczywistego, ale ważnego**

_"Zgodnie z teorią Triversa, płeć która inwestuje więcej w wychowa nie potomstwa, będzie bardziej wybredna w wyborze partnera. W przypadku naszego gatunku to kobieta wydatkuje więcej energii, związanej nie tylko z okresem ciąży, ale przede wszystkim z opieką nad dzieckiem do momentu, gdy stanie się samodzielne i nie będzie potrzebowało rodzicielskiej pomocy — ludzkie potomstwo przez bardzo długi czas pozostaje niezaradne, przez co i niezdolne do samodzielnego przetrwania. Ze względu na takie obciążenia kobiety wybierały na partnerów seksualnych tych mężczyzn, którzy byli gotowi pozostać z nimi przynajmniej do czasu, gdy wspólne potomstwo się usamodzielni, a więc byli bardziej skłonni do inwestowania rodzicielskiego. Stąd kobiece kryteria doboru partnera seksualnego stały się adaptacją, służącą rozwiązaniu problemu dotyczącego ponoszenia kosztów związanych z przyszłym potomstwem"_

[to jest fajne](http://repositorio.ulima.edu.pe/xmlui/bitstream/handle/ulima/2086/Echegaray_Marcela.pdf?sequence=1&isAllowed=y)
[to też jest fajne](https://www.ehbonline.org/article/S1090-5138(10)00075-9/fulltext)
