---
title: "Positive/neutral"
author: "Agata Zywert"
date: "24 kwietnia 2018"
output: html_document
---


##### **POZYTYWNY** 

Jesteś osobą samowystarczalną nie posiadającą silnej potrzeby, aby inni ludzie lubili Cię bądź podziwiali. Częściej akceptujesz samego siebie niż poddajesz niesłusznej samokrytyce. Masz bardzo dużo niewykorzystanej energii, którą potrafisz mądrze wykorzystać. Mimo, że możesz czuć, iż masz pewne słabe strony, twoja osobowość jest bardzo silna.

Chociaż możesz czuć się niepewny bądź zaniepokojony radzisz sobie z tym poprzez wewnętrzną dyscyplinę i kontrolę. Rzadko masz poważne wątpliwości co do podjętych przez siebie decyzji i na temat tego czy były właściwe. W razie potrzeby możesz pracować efektywnie i twórczy, nawet w przypadku zachodzących zmian i nawet jeśli występują jakieś przeciwności i ograniczenia. 

Jesteś dumny z tego, że jesteś niezależny w swoim myśleniu, ale jesteś także otwarty na opinie innych i odmienne punkty widzenia. Jesteś bardziej zdolny niż większość ludzi do bycia szczerym i otwieraniu się przed ludźmi. Chociaż jesteś ogólnie ekstrawertyczny, uprzejmy i towarzyski, masz także zdolność do czerpania przyjemności ze spędzania czasu z samym sobą. Biorąc pod uwagę twoje cechy osobowości, istnieje duża szansa, że spełnisz swoje nawet najbardziej ambitne aspiracje. 


#### **NEGATYWNY**

Potrzebujesz, aby inni ludzie lubili Cię i podziwiali. Masz tendencję do bycia samokrytycznym, gdy zachodzi potrzeba, abyś zaakceptował siebie takim jakim jesteś. Znaczna część Twojej energii nie jest do końca wykorzystywana. Posiadasz parę słabych stron, jednak przez większość czasu potrafisz sobie z nimi poradzić.

Często samozdyscyplinowanie się sprawa Ci trudność, co przeszkadza Ci w efektywnych wykonywaniu różnych czynności i zadań. Zazwyczaj jesteś pewny swoich umiejętności, jednak często martiwsz się, że nie wykorzystasz całego swojego potencjału. Czasami wątpisz, czy podjąłeś właściwą decyzję i zrobiłeś to co powinieneś. Pomimo tego, że często potrafisz osiągać efekty mimo zmian, zdarza się, że nie udaję Ci się ze względu na ograniczenia i napotkane przeciwności. 

Starasz się być niezależnym w swoich opiniach, jednak często przyjmujesz stanowisko innych bez głębszego zastanowienia. Uznajesz, że nie zawsze warto być całkiem szczerym i otwartym wobec ludzi. Czasami jesteś ekstrawertyczny, uprzejmy i towarzyski, jednak nierzadko jesteś też introwertyczny i zbyt ostrożny i powściągliwy. Niektóre z Twoich aspiracji są trochę nierealne, ale większość z nich jest osiągalna.
